# Generated by Django 5.0.7 on 2024-08-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tableEmpilhadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=255)),
                ('campo2', models.IntegerField()),
            ],
            options={
                'db_table': 'cadastro_empilhadeira',
            },
        ),
    ]
