# Generated by Django 5.0.7 on 2024-08-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_tableempilhadeira_campo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableempilhadeira',
            name='departamento',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tableempilhadeira',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tableempilhadeira',
            name='patrimonio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tableempilhadeira',
            name='secao',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tableempilhadeira',
            name='unidade',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
